name: Generate Manifest and Index

on:
  push:
    paths:
      - 'patch-d2lod/files/resurgence-patches/**'

jobs:
  generate-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Generate manifest and index.html
      run: |
        python generate_files.py
